services:
  fileshare:
    image: fileshare
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./database:/database
      - ./data:/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
