# This is a generated file. Not intended for manual editing.
services:
  fileshare:
    build:
      context: "E:\\workspace\\FileShare"
      dockerfile: "FileShare/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/FileShare.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "fileshare:dev"
    ports: []
    volumes:
    - "E:\\workspace\\FileShare\\FileShare:/app:rw"
    - "E:\\workspace\\FileShare:/src:rw"
    - "C:\\Users\\nsign\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
